apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mc
  name: mc-np
spec:
  ports:
  - name: mc-np
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: mc
  type: NodePort
status:
  loadBalancer: {}
