apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: minecraft
  name: minecraft-np
spec:
  ports:
  - name: mc-np
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: minecraft
  type: NodePort
status:
  loadBalancer: {}
