apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mc
  name: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc
  strategy: {}
  template:
    metadata:
      labels:
        app: mc
    spec:
      containers:
      - image: docker.io/itzg/minecraft-server:java17
        name: mc-server
        ports:
        - containerPort: 25565
        resources: 
          requests:
            memory: 1Gi
            cpu: 1
          limits:
            memory: 1Gi
            cpu: 1
        volumeMounts:
        - name: mc
          mountPath: /data
        envFrom:
          - configMapRef:
              name: mc-config
      volumes:
        - name: mc
          persistentVolumeClaim:
            claimName: mc-pvc
status: {}
