apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-storage
  namespace: minecraft-bedrock
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi

  
